version: "3.7"
volumes:
  database:
services:
    db:
        image: mysql:latest
        container_name: crud-mysql
        ports:
            - 3306:3306
        volumes:
            - ./init:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=crud
            - MYSQL_DATABASE=crud
            - MYSQL_USER=crud
            - MYSQL_PASSWORD=crud
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: crud-phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        links:
            - "db"
        ports:
            - 8080:80
        volumes:
            - /sessions
    app:
        build: .
        container_name: crud
        volumes:
            - .:/var/www/html
        depends_on:
            - "db"
            - "phpmyadmin"
        ports:
            - 80:80
            - 443:443